sudo: required
services:
    - docker

before_install:
    - docker build -t ak2003/frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true ak2003/frontend npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "docker"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-889862894947"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

#    DockerReact-env.eba-fcfzfpu2.ap-southeast-1.elasticbeanstalk.com