version: '3'
services: 
    web-app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
    test:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
#Recently, a bug was introduced with the latest Create React App version that is causing the React app to exit when starting with Docker Compose.
#To Resolve this:
# web:
#     stdin_open: true

### script to run with live update until unit test ###
# docker-compose up
# docker exec -it <containerId> npm run test


### script to run with live update without know containerID ###
# docker-compose up --build